import type { Config } from "tailwindcss";

export default {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        // Stitch "Lumen Script" palette
        background: "#f8f9fa",
        surface: "#f8f9fa",
        "surface-bright": "#f8f9fa",
        "surface-dim": "#d9dadb",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f4f5",
        "surface-container": "#edeeef",
        "surface-container-high": "#e7e8e9",
        "surface-container-highest": "#e1e3e4",
        "surface-variant": "#e1e3e4",
        "on-surface": "#191c1d",
        "on-surface-variant": "#434655",
        "on-background": "#191c1d",
        outline: "#747687",
        "outline-variant": "#c4c5d8",
        primary: "#003fd2",
        "on-primary": "#ffffff",
        "primary-container": "#2d5af0",
        "on-primary-container": "#e7e8ff",
        "primary-fixed": "#dde1ff",
        "primary-fixed-dim": "#b8c4ff",
        secondary: "#6b38d4",
        "on-secondary": "#ffffff",
        "secondary-container": "#8455ef",
        "on-secondary-container": "#fffbff",
        "secondary-fixed": "#e9ddff",
        "secondary-fixed-dim": "#d0bcff",
        tertiary: "#00567d",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#0070a0",
        "on-tertiary-container": "#d7ecff",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        "canvas-padding": "40px",
        "sidebar-width": "280px",
        "container-margin": "24px",
        gutter: "16px",
        "toolbar-gap": "8px",
      },
      fontFamily: {
        ui: ["Hanken Grotesk", "system-ui", "sans-serif"],
        note: ["Newsreader", "Georgia", "serif"],
        hand: ["Caveat", "cursive"],
      },
    },
  },
  plugins: [],
} satisfies Config;
